export default interface RoomCreateRequest {
    playerName: string;
    roomName: string;
    maxPlayer: number;
    /** A secret of the host, generated by its page: the API keeps its hash, to let the host reconnect the room */
    token: string;
}
