export default interface RoomJoinRequest {
    playerName: string;
    roomName: string;
    /** A secret of the player, generated by its page: the API keeps its hash while the player is in the room */
    token: string;
}
